### PR TITLE
Code cleanup for set middle C

### PR DESCRIPTION
**Pull request by walmik**
- Tweak examples
- Add minor example for transpose
- Update README
- Code cleanup
- Bump version

### CODE REVIEW

**Comment by walmik** [comment]
@ddxtanx May I request you to review this PR? It s some clean up on top of your changes. It also bumps the version.

**Comment by ddxtanx** [comment]
@walmik Sure! I'll take a look at it and get back soon.

**Comment by ddxtanx** [comment]
All looks good to me! The tests are passing, and the code definitely looks better. Thanks for these cleanups!

**Comment by walmik** [comment]
Thanks @ddxtanx !

I had one more change in here. I renamed the file setMiddleC.js to transpose.js instead. This makes it a bit more generic and true to it's purpose. It will also help us add more functionality related to transposing itself. For instance we can have a method in there that transposes a melody to another key. 

And one question I had was about the method `transposeOctave`. Can you please explain the usecase of this method? Since we have a transposeNote and scribble.midi considers the transposition before writing to a MIDI file, do we still need transposeOctave? Lemme know!

Thanks again for your time!

**Comment by ddxtanx** [comment]
Sorry about the confusing functions, I used transposeOctave to deal with the arithmetic side of the transposition (i.e. adding the transposition & returning the correct value) while transposeNote deals with the whole note string (parsing, transposing and returning the correct note.) While they could be in one function, I separated them because one strictly delt with numbers and one strictly delt with strings.

**Comment by walmik** [comment]
Thanks for the clarification, let's leave it in for now. I lol merge this in.

**Comment by walmik** [comment]
@ddxtanx Thanks for the clarification, let's leave it in for now. I lol merge this in.

**Comment by walmik** [comment]
@ddxtanx Just published v0.11. Your feature is now live :)

**Pull request merged**
